/**
 * Generated from src/v2/external-api/api.json and src/v2/source.json.
 * Do not edit this file directly. Run npm run generate:dts instead.
 */
export type APPApi = {
    users: {
        profile: {
            /** Fetches user profile details by ID. */
            fetch: (param: string) => Promise<any>;
        };
        settings: {
            /** Fetches user configuration settings by ID. */
            fetch: (param: string) => Promise<any>;
        };
    };
    reports: {
        summary: {
            /** Fetches aggregate business summary by date. */
            fetch: (param: string) => Promise<any>;
        };
        metrics: {
            /** Fetches performance metrics by date. */
            fetch: (param: string) => Promise<any>;
        };
    };
};

declare const app: APPApi;

export default app;
