/**
 * Generated by create-intellisense from src/v3.
 * Do not edit this file directly.
 */

export type AppApi = {
    founder: {
        profile: {
            /** Fetches founder and software architect profile. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        links: {
            /** Fetches official website, GitHub, NPM, and LinkedIn profile links. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
    company: {
        info: {
            /** Fetches KeshavSoft organization information and engineering philosophy. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
    ecosystem: {
        packages: {
            /** Lists flagship packages in the KeshavSoft ecosystem. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
};

declare const app: AppApi;

export default app;
